### ISSUE TITLE
Please document how to cache so that bb is not re-downloaded on each run

### ISSUE THREAD

**Issue by holyjak** [turtlequeue/setup-babashka#15]

**Comment by nha** [comment]
`setup-babashka` should also use the cache if available.
See:
- the code https://github.com/turtlequeue/setup-babashka/blob/1e886ef84f68692d42c5128245ac83e7dd38ce70/src/installer.ts#L113-L119 and https://github.com/turtlequeue/setup-babashka/blob/1e886ef84f68692d42c5128245ac83e7dd38ce70/src/installer.ts#L132-L140
- the test https://github.com/turtlequeue/setup-babashka/blob/1e886ef84f68692d42c5128245ac83e7dd38ce70/.github/workflows/self_check.yml#L22-L26
- one example run: https://github.com/turtlequeue/setup-babashka/actions/runs/4025693631/jobs/6919247271#step:4:7

Is there an indication that this is not working as expected?

**Comment by liny01-nbsa** [comment]
Hi @nha , Below log is from one of our actions, and it's been running for weeks. And this is from its latest run

![image](https://github.com/turtlequeue/setup-babashka/assets/38985073/50e69cdf-be68-4a37-8656-98c63221b6e1)

Looks, it couldn't find any cached version, and downloads bb.

This is the part of action

```yml
      - name: Install babashka v1.3.188
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: '1.3.188'


```

**Comment by liny01-nbsa** [comment]
@nha , I use the below snippet to workaround, it looks to work, is it possible that the issue is Windows only?

```yml
      - name: Cache Babashka binary (Workaround)
        uses: actions/cache@v4
        id: cache-bb
        with:
          # save-always: true
          path: C:\hostedtoolcache\windows\Babashka\1.3.188\x64
          key: ${{ runner.os }}-bb-1.3.188

      - name: Install babashka v1.3.188
        if: steps.cache-bb.outputs.cache-hit != 'true'
        uses: turtlequeue/setup-babashka@v1.5.0
        with:
          babashka-version: '1.3.188'

      - name: add bb to path
        if: steps.cache-bb.outputs.cache-hit == 'true'
        run: echo "C:\hostedtoolcache\windows\Babashka\1.3.188\x64" >> $env:GITHUB_PATH


```
